# Generated by Django 2.1.4 on 2018-12-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181222_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectGroupBindings',
            new_name='SubjectGroupBinding',
        ),
        migrations.AlterModelOptions(
            name='botbinding',
            options={'verbose_name': 'Bot Binding'},
        ),
        migrations.AlterModelOptions(
            name='participantgroupbinding',
            options={'verbose_name': 'Participant-Group Binding'},
        ),
        migrations.AlterModelOptions(
            name='subjectgroupbinding',
            options={'verbose_name': 'Subject-Group Binding'},
        ),
        migrations.AlterModelTable(
            name='botbinding',
            table='db_bot_binding',
        ),
        migrations.AlterModelTable(
            name='participantgroupbinding',
            table='db_participant_group_binding',
        ),
        migrations.AlterModelTable(
            name='subjectgroupbinding',
            table='db_subject_group_binding',
        ),
    ]
