# Generated by Django 2.1.4 on 2018-12-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181222_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
