# Generated by Django 2.1.4 on 2018-12-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181222_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer_formulation',
            field=models.CharField(max_length=6000),
        ),
    ]
