# Generated by Django 2.1.4 on 2018-12-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181223_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSpecificParticipantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('joined', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
            options={
                'verbose_name': 'Group Specific Participant Data',
                'db_table': 'db_group_specific_participant_data',
            },
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='score',
            new_name='sum_score',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='joined',
        ),
        migrations.AddField(
            model_name='groupspecificparticipantdata',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Participant'),
        ),
    ]
