# Generated by Django 2.1.4 on 2018-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181223_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telegram_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
