# Generated by Django 2.1.4 on 2018-12-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_group_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
