# Generated by Django 2.1.4 on 2018-12-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181223_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='group_specific_participant_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.GroupSpecificParticipantData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='activeProblem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='activeSubject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='chapter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='value',
            field=models.IntegerField(default=50),
        ),
    ]
