# Generated by Django 2.1.4 on 2018-12-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181223_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='activeProblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Problem'),
        ),
        migrations.AlterField(
            model_name='group',
            name='activeSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
    ]
