# Generated by Django 2.1.4 on 2018-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181223_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
