# Generated by Django 2.1.4 on 2018-12-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181230_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_min', models.IntegerField()),
                ('range_max', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Role')),
            ],
            options={
                'verbose_name': 'Score Threshold',
                'db_table': 'db_score_threshold',
            },
        ),
    ]
