# Generated by Django 2.1.4 on 2018-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_role_from_stardard_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegraphAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Telegrapg Account',
                'db_table': 'db_telegraph_account',
            },
        ),
    ]
