# Generated by Django 2.1.4 on 2018-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_telegraphaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegraphaccount',
            options={'verbose_name': 'Telegraph Account'},
        ),
        migrations.AddField(
            model_name='telegraphaccount',
            name='auth_url',
            field=models.URLField(default='https://edit.telegra.ph/auth/IHCcMVbneiGCNciQCfxV3BZcK0smmtU4aufUoohCHV'),
            preserve_default=False,
        ),
    ]
