# Generated by Django 2.1.4 on 2018-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181230_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegraphPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=150)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Telegraph Page',
                'db_table': 'db_telegraph_page',
            },
        ),
    ]
