# Generated by Django 2.1.4 on 2019-01-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_telegraphpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
