# Generated by Django 2.1.4 on 2019-01-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190104_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorPage',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_group', to='main.Group')),
            ],
            options={
                'verbose_name': 'Administrator Page',
                'db_table': 'db_administrator_page',
            },
            bases=('main.group',),
        ),
    ]
