# Generated by Django 2.1.4 on 2019-01-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_administratorpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administratorpage',
            name='group_ptr',
        ),
        migrations.AlterField(
            model_name='administratorpage',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Group'),
        ),
    ]
