# Generated by Django 2.1.4 on 2019-01-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190119_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='activeProblem',
        ),
        migrations.RemoveField(
            model_name='group',
            name='activeSubject',
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='main.Group')),
                ('activeProblem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Problem')),
                ('activeSubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
            ],
            options={
                'verbose_name': 'Participant Group',
                'db_table': 'db_participant_group',
            },
            bases=('main.group',),
        ),
        migrations.RemoveField(
            model_name='administratorpage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='botbinding',
            name='group',
        ),
        
        migrations.RemoveField(
            model_name='groupspecificparticipantdata',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subjectgroupbinding',
            name='group',
        ),
        migrations.RemoveField(
            model_name='telegraphpage',
            name='group',
        ),
        migrations.AddField(
            model_name='administratorpage',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.Group'),
            preserve_default=False,
        ),
    ]
