# Generated by Django 2.1.4 on 2019-01-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190119_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantgroup',
            name='activeSubject',
        ),
        migrations.AddField(
            model_name='participantgroup',
            name='activeSubjectGroupBinding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SubjectGroupBinding'),
        ),
    ]
