# Generated by Django 2.1.4 on 2019-01-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorpage',
            name='participant_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ParticipantGroup'),
        ),
    ]
