# Generated by Django 2.1.4 on 2019-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190202_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
