# Generated by Django 2.1.4 on 2019-02-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190202_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGroupPlayingMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Participant Group  Playing Mode',
                'db_table': 'db_participant_group_playing_mode',
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroupPlayingModePrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Participant Group Playing Mode Principal',
                'db_table': 'db_participant_group_playing_mode_principal',
            },
        ),
        migrations.AddField(
            model_name='participantgroupplayingmode',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ParticipantGroupPlayingModePrincipal'),
        ),
    ]
