# Generated by Django 2.1.4 on 2019-02-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190216_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgroupplayingmode',
            name='data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participantgroupplayingmode',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ParticipantGroupPlayingModePrincipal'),
        ),
    ]
