# Generated by Django 2.1.4 on 2019-02-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190216_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgroup',
            name='playingMode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ParticipantGroupPlayingMode'),
            preserve_default=False,
        ),
    ]
