# Generated by Django 2.1.4 on 2019-02-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_participantgroup_playingmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantDefinedProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Problem')),
                ('problem_name', models.CharField(max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Participant')),
            ],
            options={
                'verbose_name': 'Participant-defined Problem',
                'db_table': 'db_problem_participant_defined',
            },
            bases=('main.problem',),
        ),
    ]
