# Generated by Django 2.1.4 on 2019-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_participantdefinedproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='for_testing',
            field=models.BooleanField(default=False),
        ),
    ]
