# Generated by Django 2.1.4 on 2019-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190217_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
