# Generated by Django 2.1.4 on 2019-03-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_problem_answer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('for_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Problem Image',
                'db_table': 'db_problem_image',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='answer_image',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='img',
        ),
        migrations.AddField(
            model_name='problemimage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Problem'),
        ),
    ]
