# Generated by Django 2.1.4 on 2019-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20190302_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='chapter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variant_a',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variant_b',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variant_c',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variant_d',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variant_e',
            field=models.CharField(max_length=300),
        ),
    ]
