# Generated by Django 2.1.4 on 2019-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190302_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
                ('command_handler', models.CharField(max_length=200)),
                ('minimal_priority_level', models.IntegerField(default=9)),
                ('in_unregistered', models.BooleanField(default=False)),
                ('in_participant_groups', models.BooleanField(default=False)),
                ('in_administrator_pages', models.BooleanField(default=False)),
                ('needs_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telegram Command',
                'db_table': 'db_telegram_command',
            },
        ),
    ]
