# Generated by Django 2.1.4 on 2019-03-09 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_telegramcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='variants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
    ]
