# Generated by Django 2.1.4 on 2019-03-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_problem_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='variant_a',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='variant_b',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='variant_c',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='variant_d',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='variant_e',
        ),
    ]
