# Generated by Django 2.1.4 on 2019-03-09 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20190309_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='chapter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
