# Generated by Django 2.1.4 on 2019-03-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20190309_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemimage',
            name='image',
            field=models.ImageField(max_length=250, upload_to=''),
        ),
    ]
