# Generated by Django 2.1.4 on 2019-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20190310_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcommand',
            name='in_admp_needs_bound_participant_group',
            field=models.BooleanField(default=True),
        ),
    ]
