# Generated by Django 2.1.4 on 2019-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_telegramcommand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
