# Generated by Django 2.2 on 2019-04-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_group_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGroupMembersCountRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('participant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ParticipantGroup')),
            ],
            options={
                'verbose_name': 'Participant-Group Members Count Registry',
                'db_table': 'participant_group_members_count_registry',
            },
        ),
    ]
