# Generated by Django 2.2.4 on 2019-08-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_participantgroupmemberscountregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Action Type',
                'db_table': 'action_type',
            },
        ),
        migrations.CreateModel(
            name='MessageInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=100)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ActionType')),
                ('group_specific_participant_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GroupSpecificParticipantData')),
            ],
        ),
    ]
