# Generated by Django 2.2.4 on 2019-08-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_actiontype_messageinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageinstance',
            options={'verbose_name': 'Message Instance'},
        ),
        migrations.AlterModelTable(
            name='messageinstance',
            table='message_instance',
        ),
    ]
