# Generated by Django 2.2.4 on 2019-08-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20190804_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinstance',
            name='active_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Problem'),
        ),
    ]
