# Generated by Django 2.2.4 on 2019-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20190804_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinstance',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
