# Generated by Django 2.2.4 on 2019-08-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20190804_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageinstance',
            name='group_specific_participant_data',
        ),
        migrations.AddField(
            model_name='messageinstance',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Participant'),
        ),
        migrations.AddField(
            model_name='messageinstance',
            name='participant_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.ParticipantGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageinstance',
            name='message_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='actiontype',
            table='db_action_type',
        ),
        migrations.AlterModelTable(
            name='messageinstance',
            table='db_message_instance',
        ),
        migrations.AlterModelTable(
            name='participantgroupmemberscountregistry',
            table='db_participant_group_members_count_registry',
        ),
    ]
