# Generated by Django 2.2.4 on 2019-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20190804_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinstance',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
